version: "3"
services:

  search:
    build: .
    volumes:
      - .:/go/src/github.com/disiqueira/frango/src/search
    networks:
      main:
        aliases:
          - search

networks:
    main:
