// Code generated by protoc-gen-go. DO NOT EDIT.
// source: .temp/proto/search/search.proto

/*
Package search is a generated protocol buffer package.

It is generated from these files:
	.temp/proto/search/search.proto

It has these top-level messages:
	AsaFilter
	AsaList
*/
package search

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AsaFilter struct {
}

func (m *AsaFilter) Reset()                    { *m = AsaFilter{} }
func (m *AsaFilter) String() string            { return proto.CompactTextString(m) }
func (*AsaFilter) ProtoMessage()               {}
func (*AsaFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AsaList struct {
	AsaIds []string `protobuf:"bytes,1,rep,name=asaIds" json:"asaIds,omitempty"`
}

func (m *AsaList) Reset()                    { *m = AsaList{} }
func (m *AsaList) String() string            { return proto.CompactTextString(m) }
func (*AsaList) ProtoMessage()               {}
func (*AsaList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AsaList) GetAsaIds() []string {
	if m != nil {
		return m.AsaIds
	}
	return nil
}

func init() {
	proto.RegisterType((*AsaFilter)(nil), "search.AsaFilter")
	proto.RegisterType((*AsaList)(nil), "search.AsaList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Search service

type SearchClient interface {
	// Return all asas.
	Asa(ctx context.Context, in *AsaFilter, opts ...grpc.CallOption) (*AsaList, error)
}

type searchClient struct {
	cc *grpc.ClientConn
}

func NewSearchClient(cc *grpc.ClientConn) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) Asa(ctx context.Context, in *AsaFilter, opts ...grpc.CallOption) (*AsaList, error) {
	out := new(AsaList)
	err := grpc.Invoke(ctx, "/search.Search/Asa", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Search service

type SearchServer interface {
	// Return all asas.
	Asa(context.Context, *AsaFilter) (*AsaList, error)
}

func RegisterSearchServer(s *grpc.Server, srv SearchServer) {
	s.RegisterService(&_Search_serviceDesc, srv)
}

func _Search_Asa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsaFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).Asa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.Search/Asa",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).Asa(ctx, req.(*AsaFilter))
	}
	return interceptor(ctx, in, info, handler)
}

var _Search_serviceDesc = grpc.ServiceDesc{
	ServiceName: "search.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Asa",
			Handler:    _Search_Asa_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: ".temp/proto/search/search.proto",
}

func init() { proto.RegisterFile(".temp/proto/search/search.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xd7, 0x2b, 0x49, 0xcd,
	0x2d, 0xd0, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x4e, 0x4d, 0x2c, 0x4a, 0xce, 0x80, 0x52,
	0x7a, 0x60, 0x31, 0x21, 0x36, 0x08, 0x4f, 0x89, 0x9b, 0x8b, 0xd3, 0xb1, 0x38, 0xd1, 0x2d, 0x33,
	0xa7, 0x24, 0xb5, 0x48, 0x49, 0x91, 0x8b, 0xdd, 0xb1, 0x38, 0xd1, 0x27, 0xb3, 0xb8, 0x44, 0x48,
	0x8c, 0x8b, 0x2d, 0xb1, 0x38, 0xd1, 0x33, 0xa5, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0x33, 0x08,
	0xca, 0x33, 0x32, 0xe6, 0x62, 0x0b, 0x06, 0xeb, 0x14, 0xd2, 0xe4, 0x62, 0x76, 0x2c, 0x4e, 0x14,
	0x12, 0xd4, 0x83, 0x9a, 0x0b, 0x37, 0x46, 0x8a, 0x1f, 0x49, 0x08, 0x64, 0x58, 0x12, 0x1b, 0xd8,
	0x4e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x90, 0x68, 0x75, 0x9c, 0x96, 0x00, 0x00, 0x00,
}
